spring:
  application:
    name: easyCV
  devtools:
    restart:
      enabled: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${MYSQL_HOST:127.0.0.1}:${MYSQL_PORT:3306}/easycv?characterEncoding=utf-8&allowMultiQueries=true
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:fBjDSpr9-da}
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  thymeleaf:
    cache: false # 开发时关闭缓存,不然没法看到实时页面
    mode: HTML # 用非严格的 HTML
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html
    servlet:
      content-type: text/html
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
  mvc:
    static-path-pattern: /static/**
server:
  port: 9500

mybatis:
  type-aliases-package: com.mrxccc.easycv.server.domain
  mapper-locations: classpath:mapper/*.xml

#最大工作线程
record.maxsize: 10
easycv:
  easy-darwin:
    url: http://localhost:10008/api/v1/
  rtsp.play-url: rtsp://localhost:554/
  cdn-url: http://123.56.158.85/cdn/AdminLTE-3.1.0-rc/

logging:
  level:
    cn.mrxccc.easycv: debug

# 异步线程配置
# 核心线程数
async:
  executor:
    thread:
      name:
        prefix: image-record-   # 线程池中线程的名称前缀
      core_pool_size: 5  # 核心线程数
      max_pool_size: 50     # 最大线程数
      queue_capacity: 50  # 任务队列大小
      keep_alive_seconds: 100   # 缓冲队列中线程的空闲时间
