spring:
  application:
    name: easyCV
  devtools:
    restart:
      enabled: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${MYSQL_HOST:127.0.0.1}:${MYSQL_PORT:3306}/easycv?characterEncoding=utf-8&allowMultiQueries=true
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:fBjDSpr9-da}
    hikari:
      connection-timeout: 60000
      validation-timeout: 3000
      idle-timeout: 60000
      login-timeout: 5
      max-lifetime: 60000
      maximum-pool-size: 10
      minimum-idle: 10
      read-only: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,classpath:/easycv/
  mvc:
    static-path-pattern: /easycv/**
server:
  port: 9500

mybatis:
  type-aliases-package: com.mrxccc.easycv.server.domain
  mapper-locations: classpath:mapper/*.xml

#最大工作线程
record.maxsize: 10
easycv:
  easy-darwin:
    url: http://${EASY_DARWIN_IP:127.0.0.1}:${EASY_DARWIN_PORT:10008}/api/v1/
  rtsp.play-url: rtsp://${EASY_DARWIN_RTSP_URL:127.0.0.1}:${EASY_DARWIN_RTSP_PORT:554}/

logging:
  level:
    cn.mrxccc.easycv: debug

# 异步线程配置
# 核心线程数
async:
  executor:
    thread:
      name:
        prefix: image-record-   # 线程池中线程的名称前缀
      core_pool_size: 5  # 核心线程数
      max_pool_size: 50     # 最大线程数
      queue_capacity: 50  # 任务队列大小
      keep_alive_seconds: 100   # 缓冲队列中线程的空闲时间